import { CategoryConfig } from "@/lib/types";

export const CATEGORIES: CategoryConfig[] = [
  {
    id: "nature",
    name: "Nature Trails & Outdoor Exploration",
    targetCount: 12,
    keywords: [
      "park",
      "trail",
      "nature",
      "preserve",
      "outdoor",
      "hiking",
      "nature center",
      "wildlife",
      "arboretum",
      "lake",
    ],
    defaultSeasonality: ["warm"],
  },
  {
    id: "farm",
    name: "Farms & Animal Encounters",
    targetCount: 8,
    keywords: [
      "farm",
      "petting zoo",
      "animal",
      "ranch",
      "orchard",
      "pumpkin patch",
      "u-pick",
      "dairy",
    ],
    defaultSeasonality: ["warm"],
  },
  {
    id: "library",
    name: "Libraries",
    targetCount: 8,
    keywords: [
      "library",
      "public library",
      "storytime",
      "children library",
      "reading program",
    ],
    defaultSeasonality: ["warm", "winter"],
  },
  {
    id: "museum",
    name: "Museums & Educational Spots",
    targetCount: 6,
    keywords: [
      "museum",
      "children museum",
      "science center",
      "discovery",
      "planetarium",
      "history",
      "educational",
    ],
    defaultSeasonality: ["warm", "winter"],
  },
  {
    id: "indoor_play",
    name: "Indoor Play & Art Spaces",
    targetCount: 5,
    keywords: [
      "indoor play",
      "play space",
      "art studio",
      "creative",
      "gymnastics",
      "pottery",
      "craft",
      "play cafe",
    ],
    defaultSeasonality: ["winter"],
  },
  {
    id: "garden",
    name: "Gardens & Food Destinations",
    targetCount: 6,
    keywords: [
      "garden",
      "botanical",
      "farmers market",
      "community garden",
      "greenhouse",
      "bakery",
      "ice cream",
      "family restaurant",
    ],
    defaultSeasonality: ["warm"],
  },
  {
    id: "seasonal",
    name: "Seasonal & Festive Spots",
    targetCount: 6,
    keywords: [
      "festival",
      "holiday",
      "seasonal event",
      "christmas lights",
      "easter",
      "harvest",
      "parade",
      "community event",
    ],
    defaultSeasonality: ["warm", "winter"],
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  nature: "Nature Trails & Outdoor Exploration",
  farm: "Farms & Animal Encounters",
  library: "Libraries",
  museum: "Museums & Educational Spots",
  indoor_play: "Indoor Play & Art Spaces",
  garden: "Gardens & Food Destinations",
  seasonal: "Seasonal & Festive Spots",
};
