export interface WeekTheme {
  week: number;
  title: string;
  referencePlaceNote: string;
}

export type TemplateVersion = "omaha" | "lincoln" | "des_moines" | "usa";

export const TEMPLATE_VERSION_LABELS: Record<TemplateVersion, string> = {
  omaha: "Version A — Omaha",
  lincoln: "Version B — Lincoln",
  des_moines: "Version C — Des Moines",
  usa: "USA Generic",
};

export const WEEKLY_THEMES: Record<TemplateVersion, WeekTheme[]> = {
  lincoln: [
    { week: 1, title: "Warm Beginnings", referencePlaceNote: "The Mill Coffee & Tea in the Haymarket - grab a warm drink, then take a short stroll around the historic district if weather allows" },
    { week: 2, title: "Nebraska State", referencePlaceNote: "Nebraska State Capitol - Explore the Architecture" },
    { week: 3, title: "Snowflakes & Crystals", referencePlaceNote: "Morrill Hall - Explore the sparkling crystal and mineral displays, or bundle up for an outdoor frost walk to spot nature's own icy patterns" },
    { week: 4, title: "Owls & Night Skies", referencePlaceNote: "Pioneers Park Nature Center - The Prairie Building" },
    { week: 5, title: "Warmth & Light", referencePlaceNote: "Lincoln Children's Museum" },
    { week: 6, title: "Railroad History", referencePlaceNote: "Historic Haymarket District/Iron Horse Park" },
    { week: 7, title: "Kindness & Hearts", referencePlaceNote: "Local United States Post Office - Mail Valentines to loved ones" },
    { week: 8, title: "Hibernation & Rest", referencePlaceNote: "Lincoln City Libraries - snuggle into a quiet corner, pick out cozy winter reads, and enjoy a restful story time together" },
    { week: 9, title: "Winter Baking", referencePlaceNote: "Goldenrod Pastries - or a local bakery of your choice" },
    { week: 10, title: "Signs of Spring", referencePlaceNote: "Sunken Gardens" },
    { week: 11, title: "Prairie Soil & Worms", referencePlaceNote: "Larsen Tractor Test & Power Museum" },
    { week: 12, title: "Dinosaur Discoveries", referencePlaceNote: "Morrill Hall" },
    { week: 13, title: "Garden Blooms", referencePlaceNote: "Sunken Gardens" },
    { week: 14, title: "Spring on the Farm", referencePlaceNote: "The Little Red Farm — join Barnyard Storytime (every 2nd Wednesday of the month) if your week lines up, or plan a farm visit on another day to meet the animals" },
    { week: 15, title: "Weather Watchers", referencePlaceNote: "UNL Weather Station" },
    { week: 16, title: "Rainbow & Light Play", referencePlaceNote: "Lincoln Children's Museum" },
    { week: 17, title: "Garden Planting", referencePlaceNote: "UNL East Campus - Backyard Farmer Garden" },
    { week: 18, title: "Pioneers & Homesteads", referencePlaceNote: "Homestead National Historical Park" },
    { week: 19, title: "Prairie Insects", referencePlaceNote: "Spring Creek Prairie Audubon Center" },
    { week: 20, title: "Water Wonders", referencePlaceNote: "Holmes Lake" },
    { week: 21, title: "Prairie Bison & Tracks", referencePlaceNote: "Pioneers Park Nature Center" },
    { week: 22, title: "Murals & Art", referencePlaceNote: "International Quilt Museum" },
    { week: 23, title: "Strawberry Patch", referencePlaceNote: "Roca Berry Farm or Haymarket Farmers Market" },
    { week: 24, title: "Bugs, Beetles &", referencePlaceNote: "Lincoln Children's Zoo or Pioneers Park Nature Center" },
    { week: 25, title: "Zoo Adventures", referencePlaceNote: "Lincoln Children's Zoo" },
    { week: 26, title: "Earth Exploring", referencePlaceNote: "Maxwell Arboretum" },
    { week: 27, title: "Freedom, Festivities & Fun", referencePlaceNote: "Watch a Local Parade or Fireworks Show" },
    { week: 28, title: "Homegrown Goodness", referencePlaceNote: "Haymarket Farmers Market - on Saturday Morning or any Local Farmers Market" },
    { week: 29, title: "Prairie Birds & Migration", referencePlaceNote: "Wildlife Safari Park – look for owls and Bald Eagles" },
    { week: 30, title: "Prairie Wildflowers", referencePlaceNote: "Pioneers Park Prairie - for Wildflower Walks" },
    { week: 31, title: "Splash Pads & Water Play", referencePlaceNote: "Union Plaza Fountains or Antelope Park Splash Pad" },
    { week: 32, title: "Berry Sweet", referencePlaceNote: "Roca Berry Farm" },
    { week: 33, title: "Tallgrass Prairies", referencePlaceNote: "Nine-Mile Prairie" },
    { week: 34, title: "Orchard Harvest", referencePlaceNote: "Picnic Hill Orchard" },
    { week: 35, title: "Bugs & Butterflies", referencePlaceNote: "Lincoln Children's Zoo Butterfly Pavilion" },
    { week: 36, title: "Sun & Shadows", referencePlaceNote: "Mueller Tower - UNL Campus" },
    { week: 37, title: "Fall on the Farm", referencePlaceNote: "SR Pumpkin & Flower Farm" },
    { week: 38, title: "Capitol Dome & Towers", referencePlaceNote: "Nebraska State Capitol" },
    { week: 39, title: "Evening Skies", referencePlaceNote: "Hyde Observatory - or Backyard Star Gazing" },
    { week: 40, title: "Pumpkin Patch", referencePlaceNote: "Roca Berry Farm - pumpkin patch" },
    { week: 41, title: "Prairie Grasses & Seeds", referencePlaceNote: "Spring Creek Prairie Audubon Center - for seed collection" },
    { week: 42, title: "Husker's \"Go Big Red\"", referencePlaceNote: "Memorial Stadium - or Husker game day atmosphere" },
    { week: 43, title: "All Hallows' Eve", referencePlaceNote: "Boo at the Zoo @ Lincoln Children's Zoo" },
    { week: 44, title: "Halloween Fun", referencePlaceNote: "Lee's Legendary Corn Maze @ Roca Berry Farm - or trunk-or-treat event" },
    { week: 45, title: "Dancing Leaves", referencePlaceNote: "Prairie Pines or Antelope Park - for leaf collecting" },
    { week: 46, title: "Woodland Creatures", referencePlaceNote: "Wilderness Park - for animal spotting" },
    { week: 47, title: "Gratitude & Family", referencePlaceNote: "Deliver homemade gratitude cards to loved ones" },
    { week: 48, title: "Railroad Legends", referencePlaceNote: "Historic Haymarket District/Iron Horse Park" },
    { week: 49, title: "Cozying In", referencePlaceNote: "Bee Me Sensory Gym" },
    { week: 50, title: "Winter Wonders", referencePlaceNote: "Zoo Lights Powered by LES @ Lincoln Children's Zoo" },
    { week: 51, title: "Christmastide", referencePlaceNote: "Drive-through Christmas Light Show @ Star City Shores" },
    { week: 52, title: "New Year's Celebrations", referencePlaceNote: "Lincoln Children's Museum - or family celebration" },
  ],
  omaha: [
    { week: 1, title: "Cozy Beginnings", referencePlaceNote: "Playful Pines Indoor Play Park" },
    { week: 2, title: "Winter Birds", referencePlaceNote: "Fontenelle Forest Boardwalk or backyard bird feeder" },
    { week: 3, title: "Snowflakes & Crystals", referencePlaceNote: "Walk to observe frost or snow, or visit a museum with crystal displays: Possibly Joslyn Art Museum" },
    { week: 4, title: "Frozen Nebraska", referencePlaceNote: "Wherspann Lake" },
    { week: 5, title: "Warmth & Light", referencePlaceNote: "Dundee Candle Co." },
    { week: 6, title: "Arctic Animals", referencePlaceNote: "Henry Doorly Zoo" },
    { week: 7, title: "Kindness & Hearts", referencePlaceNote: "A local post office to mail out valentines to loved ones" },
    { week: 8, title: "Hibernation & Rest", referencePlaceNote: "Kids Cave Play Cafe" },
    { week: 9, title: "Baking Week", referencePlaceNote: "Sweet Magnolias Bakery & deliver baked goods to loved ones" },
    { week: 10, title: "Signs of Spring", referencePlaceNote: "Lauritzen Gardens" },
    { week: 11, title: "Worms & Soil", referencePlaceNote: "Gifford Park Community Garden" },
    { week: 12, title: "Weather Watchers", referencePlaceNote: "Schramm Park Nature Center or any museum with an active weather exhibit" },
    { week: 13, title: "Rainbows & Reflections", referencePlaceNote: "Doodle Art Studio" },
    { week: 14, title: "Buds, Blooms & Bees", referencePlaceNote: "Lauritzen Gardens" },
    { week: 15, title: "Feathered Friends", referencePlaceNote: "Heron Haven or Chalco Hills Recreation Area" },
    { week: 16, title: "Spring on the Farm", referencePlaceNote: "Scatter Joy Acres or Nelson Produce Farm" },
    { week: 17, title: "Earth Week", referencePlaceNote: "Neighborhood clean-up with Keep Omaha Beautiful" },
    { week: 18, title: "Prairie Life", referencePlaceNote: "Glacier Creek Preserve" },
    { week: 19, title: "Seeds & Sprouts", referencePlaceNote: "Mulhall's Garden Center - plant seeds or explore sprouts" },
    { week: 20, title: "Mud & Puddles", referencePlaceNote: "Zorinsky Lake Park - after a spring rainstorm" },
    { week: 21, title: "Windy Weather", referencePlaceNote: "Gerald R. Ford Birth Site Gardens" },
    { week: 22, title: "Water Wonders", referencePlaceNote: "Fontenelle Forest Wetlands or Benson Splash Pad" },
    { week: 23, title: "Strawberry Week", referencePlaceNote: "Bellevue Berry Farm, Ditmars Orchard, or Nelson's Produce Farm" },
    { week: 24, title: "Bugs, Beetles &", referencePlaceNote: "The Butterfly Pavilion at the Henry Doorly Zoo or Lauritzen Gardens" },
    { week: 25, title: "Zoo Adventures", referencePlaceNote: "Omaha's Henry Doorly Zoo & Aquarium" },
    { week: 26, title: "Wildflower Wanderings", referencePlaceNote: "Wildflower walks at Neale Woods or Hitchcock Nature Center" },
    { week: 27, title: "Patriotic Play", referencePlaceNote: "Ralston Independence Day Parade or Memorial Park Fireworks Show" },
    { week: 28, title: "Picnic Week", referencePlaceNote: "Elmwood Park or your backyard with a picnic blanket" },
    { week: 29, title: "Trains & Tracks", referencePlaceNote: "Lauritzen Gardens Railroad Garden, Kenefick Park, and/or the Durham Museum Train Exhibit" },
    { week: 30, title: "Sunshine & Shadows", referencePlaceNote: "Gene Leahy Mall" },
    { week: 31, title: "Transportation Fun", referencePlaceNote: "Strategic Air Command Museum" },
    { week: 32, title: "Dinosaurs Week", referencePlaceNote: "Omaha Children's Museum Dinosaur Exhibit or visit a Local library and read dinosaur books" },
    { week: 33, title: "River & Stream Play", referencePlaceNote: "Two Rivers State Park" },
    { week: 34, title: "Garden Harvest", referencePlaceNote: "Omaha Farmer's Market" },
    { week: 35, title: "Apple Week", referencePlaceNote: "Skinner's Fruit Farm" },
    { week: 36, title: "Grains & Gourds", referencePlaceNote: "Bellevue Berry Farm or Lauritzen Gardens" },
    { week: 37, title: "Fall on the Farm", referencePlaceNote: "Gifford Farm" },
    { week: 38, title: "Leaf Week", referencePlaceNote: "Platte River State Park - for leaf gathering" },
    { week: 39, title: "Woodland Wonders", referencePlaceNote: "Fontenelle Forest Boardwalk or Hitchcock Nature Center" },
    { week: 40, title: "Pumpkin Week", referencePlaceNote: "Vala's Pumpkin Patch, Bellevue Pumpkin Ranch or Skinny Bones Pumpkin Patch" },
    { week: 41, title: "Cozy Crafts", referencePlaceNote: "Hot Shops Art Center" },
    { week: 42, title: "Bats & Night Creatures", referencePlaceNote: "Omaha's Henry Doorly Zoo Nocturnal Exhibits" },
    { week: 43, title: "Owl & Moon Week", referencePlaceNote: "Schramm Education Center - for owl and moon exhibits" },
    { week: 44, title: "Halloween Fun", referencePlaceNote: "Omaha Children's Museum or Trunk-or-Treat Event" },
    { week: 45, title: "Fall Reflections", referencePlaceNote: "Standing Bear Lake walking paths or Memorial Park" },
    { week: 46, title: "Forest Animals", referencePlaceNote: "Wildlife Safari Park" },
    { week: 47, title: "Gratitude Week", referencePlaceNote: "A mailbox or front porch - surprise loved ones with gratitude cards" },
    { week: 48, title: "Winter Prep Week", referencePlaceNote: "Oak & Acorn Toy Store" },
    { week: 49, title: "Joyful Traditions", referencePlaceNote: "Lights Display at Gene Leahy Mall or Old Market Holiday Stroll" },
    { week: 50, title: "Winter Wonder Week", referencePlaceNote: "Lauritzen Gardens – Holiday Poinsettia Show" },
    { week: 51, title: "Christmas Week", referencePlaceNote: "Christmas at Durham Museum" },
    { week: 52, title: "New Year's Celebrations", referencePlaceNote: "The RiverFront's Holiday Lights Festival" },
  ],
  des_moines: [
    { week: 1, title: "Cozy Beginnings", referencePlaceNote: "Science Center of Iowa - Experience curiosity and wonder, with hands-on exhibits, live science demos, and a planetarium" },
    { week: 2, title: "Snowflakes & Crystals", referencePlaceNote: "State Historical Museum of Iowa - Visit to explore sparkling crystals, stones, and natural treasures from the earth" },
    { week: 3, title: "Books & Blanket Forts", referencePlaceNote: "Urbandale Public Library - A cozy hub for curiosity, learning, and community" },
    { week: 4, title: "Wonder In Motion", referencePlaceNote: "JouJou - Move, climb, and imagine in this cozy indoor play space designed for creativity and connection" },
    { week: 5, title: "Baking Week", referencePlaceNote: "La Mie Bakery - Enjoy a cozy stop for cupcakes and cocoa after your family baking day" },
    { week: 6, title: "Frosty Forest Fun", referencePlaceNote: "Arie den Boer Arboretum - Explore short trails, notice the evergreens, and discover nature up close" },
    { week: 7, title: "Hearts In Bloom", referencePlaceNote: "Local Post Office - Mail out kindness cards to loved ones" },
    { week: 8, title: "Light of the Capitol", referencePlaceNote: "Iowa State Capitol - Watch sunlight dance through the golden dome and marble halls" },
    { week: 9, title: "The Art of Play", referencePlaceNote: "Des Moines Art Center - A modern haven where art, architecture, and imagination meet" },
    { week: 10, title: "Signs of Spring", referencePlaceNote: "Greater Des Moines Botanical Garden - Spot early blooms and signs of spring in the garden" },
    { week: 11, title: "Zoo Explorers", referencePlaceNote: "Blank Park Zoo - Explore indoor exhibits and enjoy interactive discovery areas" },
    { week: 12, title: "Clover & Luck", referencePlaceNote: "Sargent Park - A peaceful green space for play, picnics, and community" },
    { week: 13, title: "Rainbows & Reflections", referencePlaceNote: "Pappajohn Sculpture Park - Spot rainbows in puddles or reflections on art" },
    { week: 14, title: "Prairie Life", referencePlaceNote: "Neal Smith National Wildlife Refuge - Walk the prairie trails and notice tall grasses, open skies, and signs of bison" },
    { week: 15, title: "Seeds & Sprouts", referencePlaceNote: "Woodlawn Community Garden - Walk along the garden beds and look closely at newly planted seeds and small sprouts" },
    { week: 16, title: "Drake Days", referencePlaceNote: "Drake University - Enjoy the excitement of the Drake relays and don't miss the famous blue oval where athletes compete!" },
    { week: 17, title: "Caring For Our Earth", referencePlaceNote: "A Local Earth Day Celebration - Or a neighborhood park participating in spring clean-up events" },
    { week: 18, title: "Buds, Blooms & Bees", referencePlaceNote: "Pella Tulip Festival - Wander through rows of blooming tulips and celebrate the peak of spring color and life" },
    { week: 19, title: "Worms & Soil", referencePlaceNote: "Playgrounds Cafe - A casual indoor play cafe where children can move, climb, and play while caregivers enjoy a relaxed break" },
    { week: 20, title: "Feathered Friends", referencePlaceNote: "Jester Park - Walk woodland and prairie trails near the Nature Center, pausing to watch birds hop, glide, and sing" },
    { week: 21, title: "Windy Weather", referencePlaceNote: "Water Works Park - Find windy spots and bring a kite" },
    { week: 22, title: "Strawberry Week", referencePlaceNote: "Des Moines City Hall - Visit the City Hall garden during strawberry season to spot ripe berries" },
    { week: 23, title: "Bugs & Butterflies", referencePlaceNote: "Christina Reiman Gardens in Ames - Observe insects and butterflies" },
    { week: 24, title: "Wildflower Wanderings", referencePlaceNote: "Neal Smith National Wildlife Refuge - Wander meadows for wildflowers" },
    { week: 25, title: "River & Stream Play", referencePlaceNote: "Raccoon River Park - Enjoy the nature walks, fun for family outings and gentle water-side activities" },
    { week: 26, title: "Picnics & Open Skies", referencePlaceNote: "Gray's Lake - Set up a family picnic in open areas" },
    { week: 27, title: "Patriotic Play", referencePlaceNote: "Urbandale 4th of July Celebration - Family festival with parade and fireworks" },
    { week: 28, title: "Water Wonders", referencePlaceNote: "Colby Park Splash Pad In Windsor Heights - Splash, wade, and wander through water" },
    { week: 29, title: "Sunshine & Shadows", referencePlaceNote: "Brown's Woods Preserve - Play with shadows in quiet woods" },
    { week: 30, title: "Trains & Tracks", referencePlaceNote: "Boone & Scenic Valley Railroad - Take a train ride and explore train history" },
    { week: 31, title: "Dinosaurs Discoveries", referencePlaceNote: "Science Center of Iowa - Explore prehistoric life or visit your local library for dinosaur discoveries" },
    { week: 32, title: "Garden Harvest", referencePlaceNote: "Des Moines Farmers' Market - Explore local harvests and colorful farm stands" },
    { week: 33, title: "State Fair Days", referencePlaceNote: "Iowa State Fair - Spend time exploring the fairgrounds, watching animals, noticing colorful displays, and enjoying the sounds, smells, and rhythms" },
    { week: 34, title: "Biking & Trails", referencePlaceNote: "High Trestle Trail Bridge - Walk, bike, or ride along this scenic trail and cross the bridge that stretches high above the Des Moines River valley" },
    { week: 35, title: "Orchard Days", referencePlaceNote: "Wills Family Orchard - Pick apples and wander through the autumn farm" },
    { week: 36, title: "Leaves & Trees", referencePlaceNote: "Greenwood - Ashworth Park - Collect colorful leaves along the forest floor" },
    { week: 37, title: "Grains & Gourds", referencePlaceNote: "Pumpkinville in Mitchellville - Wander through displays of pumpkins and gourds, noticing different shapes, textures, and colors" },
    { week: 38, title: "Woodland Wonders", referencePlaceNote: "Strasser Woods State Preserve - Explore shaded forest trails, spot acorns and moss, and listen for woodland creatures beneath the trees" },
    { week: 39, title: "Fall on the Farm", referencePlaceNote: "Living History Farms - Experience harvest season the old-fashioned way with wagon rides, animals, and hands-on fall fun" },
    { week: 40, title: "Forest Animals", referencePlaceNote: "Jester Park Nature Center - Watch for deer, squirrels, and birds along the forest trails and explore animal exhibits indoors" },
    { week: 41, title: "Owl & Moon Week", referencePlaceNote: "Brown's Woods Nature Preserve - Walk softly beneath tall trees and listen for owls and other forest animals as they settle in for the evening" },
    { week: 42, title: "Pumpkin Patch Days", referencePlaceNote: "Center Grove Orchard - Visit the pumpkin patch and orchard to experience fall sights, sounds, and simple farm fun" },
    { week: 43, title: "Bats & Night Creatures", referencePlaceNote: "Blank Park Zoo - Attend Night Eyes for a softly lit, family-friendly Halloween walk through the zoo" },
    { week: 44, title: "Halloween Fun", referencePlaceNote: "Howell's Pumpkin Patch - Enjoy wagon rides, cozy treats, and the cheerful spirit of Halloween on the prairie" },
    { week: 45, title: "Fall Reflections", referencePlaceNote: "Gray's Lake Park - Wander the lakeside paths and reflect on the changing colors mirrored in the water" },
    { week: 46, title: "Cozy Crafts", referencePlaceNote: "Des Moines Art Center - Wander the galleries for cozy indoor inspiration and gather ideas for handmade creations at home" },
    { week: 47, title: "Gratitude & Giving", referencePlaceNote: "Downtown Des Moines Holiday Market - Celebrate the season's abundance and gather in gratitude" },
    { week: 48, title: "Winter Prep", referencePlaceNote: "Ewing Park - Take a crisp fall walk through the trees as the season changes. Gather pinecones, watch for squirrels storing food, and talk about how people and animals get ready for winter" },
    { week: 49, title: "Joyful Traditions", referencePlaceNote: "Holiday Promenade - Enjoy lights and local gift shopping together" },
    { week: 50, title: "Winter Wonders", referencePlaceNote: "Greater Des Moines Botanical Garden - Step inside the glass dome to discover warm air, tropical blooms, and winter lights" },
    { week: 51, title: "Christmas Time", referencePlaceNote: "Santa's Rock n Lights at Living History Farms - Drive through tunnels of twinkling lights" },
    { week: 52, title: "New Year's Celebrations", referencePlaceNote: "Science Center of Iowa Noon Year's Eve - Ring in the new year early with bubbles, balloons, and joyful family fun" },
  ],
  usa: [
    { week: 1, title: "Cozy Beginnings", referencePlaceNote: "Take a neighborhood walk with warm drinks and notice the season changing" },
    { week: 2, title: "Winter Birds", referencePlaceNote: "Visit a local nature preserve or set up a backyard feeder" },
    { week: 3, title: "Snowflakes & Crystals", referencePlaceNote: "Go on a walk to observe frost/snow, or visit a museum with crystal displays" },
    { week: 4, title: "Frozen Landscapes", referencePlaceNote: "Explore a frozen pond or icy trail" },
    { week: 5, title: "Warmth & Light", referencePlaceNote: "Visit a candle shop, lantern-lit trail, or explore sunlight in windows" },
    { week: 6, title: "Arctic Animals", referencePlaceNote: "Visit a zoo with cold-weather animals or view a virtual Arctic tour" },
    { week: 7, title: "Kindness & Hearts", referencePlaceNote: "A local post office to mail out valentines to loved ones" },
    { week: 8, title: "Hibernation & Rest", referencePlaceNote: "Make a blanket fort or take a quiet walk on a winter trail" },
    { week: 9, title: "Baking Week", referencePlaceNote: "Visit a bakery or deliver baked goods to friends" },
    { week: 10, title: "Signs of Spring", referencePlaceNote: "Visit a botanical garden or take a spring scavenger hunt walk" },
    { week: 11, title: "Worms & Soil", referencePlaceNote: "Visit a community garden or dig in your backyard soil" },
    { week: 12, title: "Weather Watchers", referencePlaceNote: "Visit a garden, museum exhibit, or observe weather outdoors" },
    { week: 13, title: "Rainbows & Reflections", referencePlaceNote: "Walk near a pond, stream, or puddles to see reflections" },
    { week: 14, title: "Buds, Blooms & Bees", referencePlaceNote: "Visit a pollinator garden or flowerbed in bloom" },
    { week: 15, title: "Feathered Friends", referencePlaceNote: "Visit a local duck pond or park with birds" },
    { week: 16, title: "Spring on the Farm", referencePlaceNote: "Visit a local farm, petting zoo, or farmers market" },
    { week: 17, title: "Earth Week", referencePlaceNote: "Join a neighborhood clean-up or do one in your yard/schoolyard" },
    { week: 18, title: "Prairie Life", referencePlaceNote: "Walk through tall grass, meadows, or open fields nearby" },
    { week: 19, title: "Seeds & Sprouts", referencePlaceNote: "Visit a garden center or plant seeds at home" },
    { week: 20, title: "Mud & Puddles", referencePlaceNote: "Go to a park after a rainstorm and find puddles & mud" },
    { week: 21, title: "Windy Weather", referencePlaceNote: "Visit a breezy park, meadow, or open field" },
    { week: 22, title: "Water Wonders", referencePlaceNote: "Visit a splash pad, creek, or wetland trail" },
    { week: 23, title: "Strawberry Week", referencePlaceNote: "Pick strawberries at a u-pick farm or shop at the grocery's berry section" },
    { week: 24, title: "Bugs, Beetles &", referencePlaceNote: "Visit a butterfly garden, insect exhibit, or nature trail" },
    { week: 25, title: "Zoo Adventures", referencePlaceNote: "Visit a local zoo, wildlife park, or animal sanctuary" },
    { week: 26, title: "Wildflower Wanderings", referencePlaceNote: "Walk in a wildflower field or garden trail" },
    { week: 27, title: "Patriotic Play", referencePlaceNote: "Attend a parade, fireworks display, or community festival" },
    { week: 28, title: "Picnic Week", referencePlaceNote: "Have a picnic at a local park or in your backyard" },
    { week: 29, title: "Trains & Tracks", referencePlaceNote: "Visit a train museum, ride a community train, or set up toy tracks at home" },
    { week: 30, title: "Sunshine & Shadows", referencePlaceNote: "Play outdoors with shadow puppets in a sunny spot" },
    { week: 31, title: "Transportation Fun", referencePlaceNote: "Visit a transportation museum, airport lookout, or vehicle show" },
    { week: 32, title: "Dinosaurs Week", referencePlaceNote: "Visit a museum exhibit, library display, or read dinosaur books at home" },
    { week: 33, title: "River & Stream Play", referencePlaceNote: "Visit a river, creek, or nature trail with water" },
    { week: 34, title: "Garden Harvest", referencePlaceNote: "Visit a farmers market or community garden" },
    { week: 35, title: "Apple Week", referencePlaceNote: "Pick apples at a local orchard or buy a variety to taste at the store" },
    { week: 36, title: "Grains & Gourds", referencePlaceNote: "Visit a farmers market or local farm stand to explore pumpkins, squash, and grains" },
    { week: 37, title: "Fall on the Farm", referencePlaceNote: "Visit a pumpkin patch, fall farm festival, or harvest event" },
    { week: 38, title: "Leaf Week", referencePlaceNote: "Visit a park with trees to gather and play in leaves" },
    { week: 39, title: "Woodland Wonders", referencePlaceNote: "Take a walk in the forest or wooded trails" },
    { week: 40, title: "Pumpkin Week", referencePlaceNote: "Visit a pumpkin patch, fall festival, or farm stand" },
    { week: 41, title: "Cozy Crafts", referencePlaceNote: "Visit a craft store, art studio, or make crafts at home" },
    { week: 42, title: "Bats & Night Creatures", referencePlaceNote: "Visit a nocturnal animal exhibit or read under flashlights at home" },
    { week: 43, title: "Owl & Moon Week", referencePlaceNote: "Visit a nature center or go on an evening moon walk" },
    { week: 44, title: "Halloween Fun", referencePlaceNote: "Attend a trick-or-treat or community Halloween event" },
    { week: 45, title: "Fall Reflections", referencePlaceNote: "Visit a park or trail to enjoy fall colors" },
    { week: 46, title: "Forest Animals", referencePlaceNote: "Visit a zoo, wildlife park, or forest trail" },
    { week: 47, title: "Gratitude Week", referencePlaceNote: "Volunteer, donate, or make and deliver gratitude cards to loved ones" },
    { week: 48, title: "Winter Prep Week", referencePlaceNote: "Visit a local market, winter fair, or organize winter clothes at home" },
    { week: 49, title: "Joyful Traditions", referencePlaceNote: "Visit a holiday lights display, tree lot, or festive market" },
    { week: 50, title: "Winter Wonder Week", referencePlaceNote: "Visit a children's museum, winter exhibit, or play in snow/ice outdoors" },
    { week: 51, title: "Christmas Week", referencePlaceNote: "Visit a holiday lights display, Christmas market, or tree farm" },
    { week: 52, title: "New Year's Celebrations", referencePlaceNote: "Attend a community lights festival, family-friendly countdown, or celebrate at home" },
  ],
};

export function getSeason(week: number): "winter" | "spring" | "summer" | "fall" {
  if (week >= 1 && week <= 9) return "winter";
  if (week >= 10 && week <= 22) return "spring";
  if (week >= 23 && week <= 35) return "summer";
  if (week >= 36 && week <= 48) return "fall";
  return "winter"; // 49-52
}
